development:
  adapter: postgresql
  encoding: unicode
  database: sample_app_development
  pool: 5
  username: mateusz
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: sample_app_tests
  pool: 5
  username: mateusz
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: sample_app
  pool: 5
  username: mateusz
  password:


